;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
bg = #0b1220
fg = #cbd5f5
blue = #4f7cff
red = #ff4d5a
white = #ffffff
black = #000000
muted = #6b7280
border = #1e293b
transparent = #00000000

##################
#       BAR      #
##################

# Bar
[bar/bar]
bottom = true
width = 99.3%
height = 50
# radius = 4
offset-x = 7
offset-y = 8
background = ${colors.bg}
foreground = ${colors.fg}
border-color = ${colors.white}
override-redirect = false
wm-restack = bspwm
# dock = true
enable-ipc = true

font-0 = "Liberation:size=12;2"
font-1 = "Symbols Nerd Font:size=12;2"
font-2 = "Liberation:size=12;12"

; modules-left = workspaces player
modules-left = workspaces 
modules-center = clock 
modules-right = temperature pulseaudio spacer cpu memory

#####################
#      MODULES      #
#####################

[module/workspaces]
type = internal/xworkspaces
format-margin = 3
; label-active = %name%
label-active = ●
label-active-foreground = ${colors.white}
label-active-font = 2
label-active-padding = 1

# Not active (has windows)
label-occupied = ●
label-occupied-foreground = ${colors.muted}
label-occupied-padding = 1

# Not active (no windows)
label-empty = ●
label-empty-foreground = ${colors.muted}
label-empty-padding = 1

[module/player]
type = custom/script
exec = playerctl metadata --format '{{ title }}'
interval = 1

click-left = playerctl play-pause
click-right = playerctl next
click-middle = playerctl previous

label = %output%
label-maxlen = 30

[module/clock]
type = internal/date
interval = 1
; note: make time text bold
date = %{F#ffffff} %I:%M %p %{F#888888} • %a %d 
label-foreground = ${colors.white}

[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
hwmon-path = /sys/class/hwmon/hwmon2/temp1_input
base-temperature = 20
warn-temperature = 80

format = <ramp> <label>
format-warn = <ramp> <label-warn>

ramp-0 = 
ramp-1 = 
ramp-2 = 

label = %temperature-c%
label-warn = TEMP %temperature-c% (WARM!)
label-warn-foreground = #f00

[module/pulseaudio]
type = internal/pulseaudio

label-volume = %percentage%
label-muted =  
label-muted-foreground = #999

format-volume = <ramp-volume> <label-volume>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

click-right = pavucontrol

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.white}
label = %percentage%%

[module/memory]
type = internal/memory
interval = 3
format-margin = 4
format-prefix = " "
format-prefix-foreground = ${colors.white}
label = %percentage_used%%

[module/spacer]
type = custom/text
content = "   "

[settings]
screenchange-reload = true
pseudo-transparency = true 
